name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build Java Application
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '23'
          cache: maven

      - name: Build application
        run: mvn clean package