name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  build:
    name: Build and SonarCloud
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Build application
        run: mvn clean package

      - name: SonarCloud analysis
        run: >
          mvn sonar:sonar
          -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}